name: nazvanie
on:
  push:
    branches:
      - main
      - develop
jobs:
  check-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Repository check
        run: echo "Repository updated"
