name: nazvanie
on:
 push:
  branches:
   - main
   - develop
jobs:
 check-project:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Repositoey check
   run: echo "Repository updated"
